"""add menu

Revision ID: 0e9bb1dab0fb
Revises: 37f0f7e30438
Create Date: 2022-05-21 16:02:24.080342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e9bb1dab0fb"
down_revision = "37f0f7e30438"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "create_time",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("is_delete", sa.Boolean(), nullable=False, comment="是否删除"),
        sa.Column("menu_name", sa.String(length=32), nullable=False, comment="菜单名称"),
        sa.Column("menu_level", sa.Integer(), nullable=False, comment="菜单层级"),
        sa.Column("menu_order", sa.Integer(), nullable=False, comment="菜单排序(从小到大排)"),
        sa.Column(
            "menu_type", sa.SmallInteger(), nullable=False, comment="菜单类型(1:菜单 2:按钮)"
        ),
        sa.Column(
            "route_key",
            sa.String(length=128),
            nullable=False,
            comment="路由key,可以通过key获取到对应的路由",
        ),
        sa.Column("is_visible", sa.Boolean(), nullable=False, comment="菜单本身是否可见"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_menu")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu_menu")
    # ### end Alembic commands ###
