"""add permission

Revision ID: 2bdde1bca83d
Revises: 980ee6bb7ff0
Create Date: 2022-05-21 16:43:56.612784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdde1bca83d'
down_revision = '980ee6bb7ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色id'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单id'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否有查看权限'),
    sa.Column('is_operate', sa.Boolean(), nullable=False, comment='是否有操作权限'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_permission')),
    sa.UniqueConstraint('role_id', 'menu_id', name=op.f('uq_permission_permission_role_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_permission')
    # ### end Alembic commands ###
