"""user add is_admin

Revision ID: 37f0f7e30438
Revises: 65e661e477f0
Create Date: 2022-05-21 15:42:21.228549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f0f7e30438'
down_revision = '65e661e477f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否是管理员, 管理员有所有权限'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_user', 'is_admin')
    # ### end Alembic commands ###
