"""user change is_delete

Revision ID: 65e661e477f0
Revises: 7d96f29c188b
Create Date: 2022-05-21 15:06:32.894189

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "65e661e477f0"
down_revision = "7d96f29c188b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account_user",
        "is_delete",
        existing_type=mysql.SMALLINT(display_width=6),
        comment="是否删除",
        existing_comment="是否删除 0否 1是",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account_user",
        "is_delete",
        existing_type=mysql.SMALLINT(display_width=6),
        comment="是否删除 0否 1是",
        existing_comment="是否删除",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
