"""remove union_id except user

Revision ID: 6c23cd365b80
Revises: f23b22211d7c
Create Date: 2022-06-07 17:40:55.907212

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6c23cd365b80"
down_revision = "f23b22211d7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_menu_menu_union_id", table_name="menu_menu")
    op.drop_column("menu_menu", "union_id")
    op.drop_index(
        "uq_permission_permission_union_id", table_name="permission_permission"
    )
    op.drop_column("permission_permission", "union_id")
    op.drop_index("uq_permission_role_union_id", table_name="permission_role")
    op.drop_column("permission_role", "union_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_role",
        sa.Column(
            "union_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="关联id",
        ),
    )
    op.create_index(
        "uq_permission_role_union_id", "permission_role", ["union_id"], unique=False
    )
    op.add_column(
        "permission_permission",
        sa.Column(
            "union_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="关联id",
        ),
    )
    op.create_index(
        "uq_permission_permission_union_id",
        "permission_permission",
        ["union_id"],
        unique=False,
    )
    op.add_column(
        "menu_menu",
        sa.Column(
            "union_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="关联id",
        ),
    )
    op.create_index("uq_menu_menu_union_id", "menu_menu", ["union_id"], unique=False)
    # ### end Alembic commands ###
