"""permission remove unique key

Revision ID: 766ed1708c37
Revises: fc61ad568cbc
Create Date: 2022-06-10 10:16:05.449455

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "766ed1708c37"
down_revision = "fc61ad568cbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_permission_permission_role_id", table_name="permission_permission"
    )
    op.create_index(
        op.f("ix_permission_permission_menu_id"),
        "permission_permission",
        ["menu_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_permission_role_id"),
        "permission_permission",
        ["role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_permission_permission_role_id"), table_name="permission_permission"
    )
    op.drop_index(
        op.f("ix_permission_permission_menu_id"), table_name="permission_permission"
    )
    op.create_index(
        "uq_permission_permission_role_id",
        "permission_permission",
        ["role_id", "menu_id"],
        unique=False,
    )
    # ### end Alembic commands ###
