"""user add password

Revision ID: 7a615743cb3d
Revises: bf48bbe0de7c
Create Date: 2022-05-17 18:21:31.152962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a615743cb3d"
down_revision = "bf48bbe0de7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_user",
        sa.Column("password", sa.String(length=60), nullable=False, comment="密码"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account_user", "password")
    # ### end Alembic commands ###
