"""user add login_id

Revision ID: 7d96f29c188b
Revises: 436c302a4253
Create Date: 2022-05-18 10:17:09.353615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d96f29c188b'
down_revision = '436c302a4253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('login_id', sa.String(length=36), nullable=False, comment='登录id'))
    op.create_unique_constraint(op.f('uq_account_user_login_id'), 'account_user', ['login_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_account_user_login_id'), 'account_user', type_='unique')
    op.drop_column('account_user', 'login_id')
    # ### end Alembic commands ###
