"""add role

Revision ID: 980ee6bb7ff0
Revises: 0e9bb1dab0fb
Create Date: 2022-05-21 16:40:32.344377

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "980ee6bb7ff0"
down_revision = "0e9bb1dab0fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "create_time",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("is_delete", sa.Boolean(), nullable=False, comment="是否删除"),
        sa.Column("role_name", sa.String(length=32), nullable=False, comment="角色名称"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_role")),
    )
    op.create_table(
        "permission_role_user",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "role_id", "user_id", name=op.f("pk_permission_role_user")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission_role_user")
    op.drop_table("permission_role")
    # ### end Alembic commands ###
