"""add role_permission

Revision ID: aef7928e56ed
Revises: eb23f5a99e07
Create Date: 2022-05-23 23:29:40.338744

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "aef7928e56ed"
down_revision = "eb23f5a99e07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_permission_permission_role_id", table_name="permission_permission"
    )
    op.create_unique_constraint(
        op.f("uq_permission_permission_menu_id"), "permission_permission", ["menu_id"]
    )
    op.drop_column("permission_permission", "role_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_permission",
        sa.Column(
            "role_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="角色id",
        ),
    )
    op.drop_constraint(
        op.f("uq_permission_permission_menu_id"),
        "permission_permission",
        type_="unique",
    )
    op.create_index(
        "uq_permission_permission_role_id",
        "permission_permission",
        ["role_id", "menu_id"],
        unique=False,
    )
    # ### end Alembic commands ###
