"""user unique nickname

Revision ID: e7fe4e0d4ab8
Revises: b7bb443b54ab
Create Date: 2022-05-17 17:49:13.775237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7fe4e0d4ab8'
down_revision = 'b7bb443b54ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='昵称',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_account_user_nickname'), 'account_user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_account_user_nickname'), 'account_user', type_='unique')
    op.alter_column('account_user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment='昵称',
               existing_nullable=False)
    # ### end Alembic commands ###
