"""menu remove menu_level

Revision ID: eb23f5a99e07
Revises: 725702ba3a35
Create Date: 2022-05-22 00:02:39.455609

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "eb23f5a99e07"
down_revision = "725702ba3a35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_menu", "menu_level")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_menu",
        sa.Column(
            "menu_level",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="菜单层级",
        ),
    )
    # ### end Alembic commands ###
