"""add union_id

Revision ID: f23b22211d7c
Revises: aef7928e56ed
Create Date: 2022-06-07 14:29:39.705982

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f23b22211d7c"
down_revision = "aef7928e56ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_user",
        sa.Column("union_id", sa.String(length=36), nullable=False, comment="关联id"),
    )
    op.drop_index("uq_account_user_login_id", table_name="account_user")
    op.create_unique_constraint(
        op.f("uq_account_user_union_id"), "account_user", ["union_id"]
    )
    op.drop_column("account_user", "login_id")
    op.add_column(
        "menu_menu",
        sa.Column("union_id", sa.String(length=36), nullable=False, comment="关联id"),
    )
    op.create_unique_constraint(
        op.f("uq_menu_menu_union_id"), "menu_menu", ["union_id"]
    )
    op.add_column(
        "permission_permission",
        sa.Column("union_id", sa.String(length=36), nullable=False, comment="关联id"),
    )
    op.create_unique_constraint(
        op.f("uq_permission_permission_union_id"), "permission_permission", ["union_id"]
    )
    op.add_column(
        "permission_role",
        sa.Column("union_id", sa.String(length=36), nullable=False, comment="关联id"),
    )
    op.create_unique_constraint(
        op.f("uq_permission_role_union_id"), "permission_role", ["union_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_permission_role_union_id"), "permission_role", type_="unique"
    )
    op.drop_column("permission_role", "union_id")
    op.drop_constraint(
        op.f("uq_permission_permission_union_id"),
        "permission_permission",
        type_="unique",
    )
    op.drop_column("permission_permission", "union_id")
    op.drop_constraint(op.f("uq_menu_menu_union_id"), "menu_menu", type_="unique")
    op.drop_column("menu_menu", "union_id")
    op.add_column(
        "account_user",
        sa.Column(
            "login_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="登录id",
        ),
    )
    op.drop_constraint(op.f("uq_account_user_union_id"), "account_user", type_="unique")
    op.create_index(
        "uq_account_user_login_id", "account_user", ["login_id"], unique=False
    )
    op.drop_column("account_user", "union_id")
    # ### end Alembic commands ###
