"""permission add role

Revision ID: fc61ad568cbc
Revises: 6c23cd365b80
Create Date: 2022-06-07 17:50:19.263298

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc61ad568cbc"
down_revision = "6c23cd365b80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_permission",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色id"),
    )
    op.drop_index(
        "uq_permission_permission_menu_id", table_name="permission_permission"
    )
    op.create_unique_constraint(
        op.f("uq_permission_permission_role_id"),
        "permission_permission",
        ["role_id", "menu_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_permission_permission_role_id"),
        "permission_permission",
        type_="unique",
    )
    op.create_index(
        "uq_permission_permission_menu_id",
        "permission_permission",
        ["menu_id"],
        unique=False,
    )
    op.drop_column("permission_permission", "role_id")
    # ### end Alembic commands ###
